Reintroduced pagination to the products page
idx-academy/spa-orders pull request #454
Opened 2024-08-05 13:45 UTC by ValKoDim

I reverted the changes to pagination to the products page. Also made some adjustments to our mock backend, to better replicate the backend logic.

https://github.com/user-attachments/assets/c68b5bf6-fcec-44b3-9a42-6ccbccf5faf7

2024-08-05 14:11 UTC, GeorgeShvab commented on code/src/pages/products/ProductsPage.tsx
> +  console.log(productsList);
Remove `console.log(productsList)`

2024-08-05 15:04 UTC, mhevyk approved these changes

2024-08-05 17:12 UTC, OliaHrytsak commented
This is how the last page looks like
Its not good. Try to fix it
![image](https://github.com/user-attachments/assets/b471d8eb-ada4-4544-a5c6-cba909ff8bf3)

2024-08-05 17:15 UTC, OliaHrytsak requested changes
This is how the last page looks like
Its not good. Try to fix it
![image](https://github.com/user-attachments/assets/b471d8eb-ada4-4544-a5c6-cba909ff8bf3)

2024-08-06 09:31 UTC, ValKoDim commented on code/src/pages/products/ProductsPage.tsx
> +  console.log(productsList);
Done

2024-08-06 09:31 UTC, ValKoDim commented
> This is how the last page looks like Its not good. Try to fix it ![image](https://private-user-images.githubusercontent.com/127191734/355185934-b471d8eb-ada4-4544-a5c6-cba909ff8bf3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MzY5NTQsIm5iZiI6MTcyMjkzNjY1NCwicGF0aCI6Ii8xMjcxOTE3MzQvMzU1MTg1OTM0LWI0NzFkOGViLWFkYTQtNDU0NC1hNWM2LWNiYTkwOWZmOGJmMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNlQwOTMwNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNGZjNDJiYjkyMmExNjc1N2QyZGNkMTE4ZDkyMTFjNWU3MmMyOTNjMzQzYzk0ZWQwNTUxY2M3NjFjMWNjMWEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dF4FnzM0SvE9P_5VZ4Lgbi8mh6yN1LLIuz-SgNCS3Ys)

@OliaHrytsak   Check changes

2024-08-06 09:36 UTC, OliaHrytsak approved these changes

2024-08-06 10:15 UTC, GeorgeShvab approved these changes

2024-08-06 10:34 UTC, merged